pipeline {
    agent any
    
    tools {
        jdk 'JAVA11'
        maven 'mv392'
    }

    environment{
        REGISTRYLOCATION = "https://www.google.com/"
    }
    
    stages {
           stage('Initialize'){
            steps{
                script{
                        env.PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
                       
                    }
                }
             }   
            stage('Which Java?') {
                steps {
                    script{
                        
                        sh 'java --version'
                    }
                }
            }
            stage ('Build') {
                steps {
                    script{
                        
                        sh "echo $JAVA_HOME"
                        sh "echo $M2_HOME"
                        sh "echo $PATH"
                        sh "mvn -version"
                    }
                }    
            }
    }
}