pipeline {
    agent any
    
    tools {
        jdk 'java11'
        maven 'maven392'
    }

    enviroment{
        JAVA_HOME = '${jdk}'
    }
    
    stages {
            stage('Which Java?') {
                steps {
                    sh 'java --version'
                }
            }
            stage ('Build') {
                steps {
                    sh "mvn clean verify"
                }    
            }
    }
}