pipeline {
    agent any
    
    tools {
        jdk 'java11'
    }
    
    stages {
            stage('Which Java?') {
                steps {
                    sh 'java --version'
                }
            }
    }
}